import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const elements = [
  { id: 1,   symbol: "H",  nameJa: "水素",       nameEn: "Hydrogen",      category: "非金属",         period: 1, group: 1,    atomicWeight: 1.008 },
  { id: 2,   symbol: "He", nameJa: "ヘリウム",   nameEn: "Helium",        category: "希ガス",         period: 1, group: 18,   atomicWeight: 4.003 },
  { id: 3,   symbol: "Li", nameJa: "リチウム",   nameEn: "Lithium",       category: "アルカリ金属",   period: 2, group: 1,    atomicWeight: 6.941 },
  { id: 4,   symbol: "Be", nameJa: "ベリリウム", nameEn: "Beryllium",     category: "アルカリ土類金属",period: 2, group: 2,   atomicWeight: 9.012 },
  { id: 5,   symbol: "B",  nameJa: "ホウ素",     nameEn: "Boron",         category: "半金属",         period: 2, group: 13,   atomicWeight: 10.81 },
  { id: 6,   symbol: "C",  nameJa: "炭素",       nameEn: "Carbon",        category: "非金属",         period: 2, group: 14,   atomicWeight: 12.011 },
  { id: 7,   symbol: "N",  nameJa: "窒素",       nameEn: "Nitrogen",      category: "非金属",         period: 2, group: 15,   atomicWeight: 14.007 },
  { id: 8,   symbol: "O",  nameJa: "酸素",       nameEn: "Oxygen",        category: "非金属",         period: 2, group: 16,   atomicWeight: 15.999 },
  { id: 9,   symbol: "F",  nameJa: "フッ素",     nameEn: "Fluorine",      category: "ハロゲン",       period: 2, group: 17,   atomicWeight: 18.998 },
  { id: 10,  symbol: "Ne", nameJa: "ネオン",     nameEn: "Neon",          category: "希ガス",         period: 2, group: 18,   atomicWeight: 20.180 },
  { id: 11,  symbol: "Na", nameJa: "ナトリウム", nameEn: "Sodium",        category: "アルカリ金属",   period: 3, group: 1,    atomicWeight: 22.990 },
  { id: 12,  symbol: "Mg", nameJa: "マグネシウム",nameEn: "Magnesium",   category: "アルカリ土類金属",period: 3, group: 2,   atomicWeight: 24.305 },
  { id: 13,  symbol: "Al", nameJa: "アルミニウム",nameEn: "Aluminum",    category: "後遷移金属",     period: 3, group: 13,   atomicWeight: 26.982 },
  { id: 14,  symbol: "Si", nameJa: "ケイ素",     nameEn: "Silicon",       category: "半金属",         period: 3, group: 14,   atomicWeight: 28.086 },
  { id: 15,  symbol: "P",  nameJa: "リン",       nameEn: "Phosphorus",    category: "非金属",         period: 3, group: 15,   atomicWeight: 30.974 },
  { id: 16,  symbol: "S",  nameJa: "硫黄",       nameEn: "Sulfur",        category: "非金属",         period: 3, group: 16,   atomicWeight: 32.060 },
  { id: 17,  symbol: "Cl", nameJa: "塩素",       nameEn: "Chlorine",      category: "ハロゲン",       period: 3, group: 17,   atomicWeight: 35.450 },
  { id: 18,  symbol: "Ar", nameJa: "アルゴン",   nameEn: "Argon",         category: "希ガス",         period: 3, group: 18,   atomicWeight: 39.948 },
  { id: 19,  symbol: "K",  nameJa: "カリウム",   nameEn: "Potassium",     category: "アルカリ金属",   period: 4, group: 1,    atomicWeight: 39.098 },
  { id: 20,  symbol: "Ca", nameJa: "カルシウム", nameEn: "Calcium",       category: "アルカリ土類金属",period: 4, group: 2,   atomicWeight: 40.078 },
  { id: 21,  symbol: "Sc", nameJa: "スカンジウム",nameEn: "Scandium",    category: "遷移金属",       period: 4, group: 3,    atomicWeight: 44.956 },
  { id: 22,  symbol: "Ti", nameJa: "チタン",     nameEn: "Titanium",      category: "遷移金属",       period: 4, group: 4,    atomicWeight: 47.867 },
  { id: 23,  symbol: "V",  nameJa: "バナジウム", nameEn: "Vanadium",      category: "遷移金属",       period: 4, group: 5,    atomicWeight: 50.942 },
  { id: 24,  symbol: "Cr", nameJa: "クロム",     nameEn: "Chromium",      category: "遷移金属",       period: 4, group: 6,    atomicWeight: 51.996 },
  { id: 25,  symbol: "Mn", nameJa: "マンガン",   nameEn: "Manganese",     category: "遷移金属",       period: 4, group: 7,    atomicWeight: 54.938 },
  { id: 26,  symbol: "Fe", nameJa: "鉄",         nameEn: "Iron",          category: "遷移金属",       period: 4, group: 8,    atomicWeight: 55.845 },
  { id: 27,  symbol: "Co", nameJa: "コバルト",   nameEn: "Cobalt",        category: "遷移金属",       period: 4, group: 9,    atomicWeight: 58.933 },
  { id: 28,  symbol: "Ni", nameJa: "ニッケル",   nameEn: "Nickel",        category: "遷移金属",       period: 4, group: 10,   atomicWeight: 58.693 },
  { id: 29,  symbol: "Cu", nameJa: "銅",         nameEn: "Copper",        category: "遷移金属",       period: 4, group: 11,   atomicWeight: 63.546 },
  { id: 30,  symbol: "Zn", nameJa: "亜鉛",       nameEn: "Zinc",          category: "遷移金属",       period: 4, group: 12,   atomicWeight: 65.380 },
  { id: 31,  symbol: "Ga", nameJa: "ガリウム",   nameEn: "Gallium",       category: "後遷移金属",     period: 4, group: 13,   atomicWeight: 69.723 },
  { id: 32,  symbol: "Ge", nameJa: "ゲルマニウム",nameEn: "Germanium",   category: "半金属",         period: 4, group: 14,   atomicWeight: 72.630 },
  { id: 33,  symbol: "As", nameJa: "ヒ素",       nameEn: "Arsenic",       category: "半金属",         period: 4, group: 15,   atomicWeight: 74.922 },
  { id: 34,  symbol: "Se", nameJa: "セレン",     nameEn: "Selenium",      category: "非金属",         period: 4, group: 16,   atomicWeight: 78.971 },
  { id: 35,  symbol: "Br", nameJa: "臭素",       nameEn: "Bromine",       category: "ハロゲン",       period: 4, group: 17,   atomicWeight: 79.904 },
  { id: 36,  symbol: "Kr", nameJa: "クリプトン", nameEn: "Krypton",       category: "希ガス",         period: 4, group: 18,   atomicWeight: 83.798 },
  { id: 37,  symbol: "Rb", nameJa: "ルビジウム", nameEn: "Rubidium",      category: "アルカリ金属",   period: 5, group: 1,    atomicWeight: 85.468 },
  { id: 38,  symbol: "Sr", nameJa: "ストロンチウム",nameEn: "Strontium", category: "アルカリ土類金属",period: 5, group: 2,   atomicWeight: 87.620 },
  { id: 39,  symbol: "Y",  nameJa: "イットリウム",nameEn: "Yttrium",     category: "遷移金属",       period: 5, group: 3,    atomicWeight: 88.906 },
  { id: 40,  symbol: "Zr", nameJa: "ジルコニウム",nameEn: "Zirconium",   category: "遷移金属",       period: 5, group: 4,    atomicWeight: 91.224 },
  { id: 41,  symbol: "Nb", nameJa: "ニオブ",     nameEn: "Niobium",       category: "遷移金属",       period: 5, group: 5,    atomicWeight: 92.906 },
  { id: 42,  symbol: "Mo", nameJa: "モリブデン", nameEn: "Molybdenum",    category: "遷移金属",       period: 5, group: 6,    atomicWeight: 95.950 },
  { id: 43,  symbol: "Tc", nameJa: "テクネチウム",nameEn: "Technetium",  category: "遷移金属",       period: 5, group: 7,    atomicWeight: null },
  { id: 44,  symbol: "Ru", nameJa: "ルテニウム", nameEn: "Ruthenium",     category: "遷移金属",       period: 5, group: 8,    atomicWeight: 101.07 },
  { id: 45,  symbol: "Rh", nameJa: "ロジウム",   nameEn: "Rhodium",       category: "遷移金属",       period: 5, group: 9,    atomicWeight: 102.91 },
  { id: 46,  symbol: "Pd", nameJa: "パラジウム", nameEn: "Palladium",     category: "遷移金属",       period: 5, group: 10,   atomicWeight: 106.42 },
  { id: 47,  symbol: "Ag", nameJa: "銀",         nameEn: "Silver",        category: "遷移金属",       period: 5, group: 11,   atomicWeight: 107.87 },
  { id: 48,  symbol: "Cd", nameJa: "カドミウム", nameEn: "Cadmium",       category: "遷移金属",       period: 5, group: 12,   atomicWeight: 112.41 },
  { id: 49,  symbol: "In", nameJa: "インジウム", nameEn: "Indium",        category: "後遷移金属",     period: 5, group: 13,   atomicWeight: 114.82 },
  { id: 50,  symbol: "Sn", nameJa: "スズ",       nameEn: "Tin",           category: "後遷移金属",     period: 5, group: 14,   atomicWeight: 118.71 },
  { id: 51,  symbol: "Sb", nameJa: "アンチモン", nameEn: "Antimony",      category: "半金属",         period: 5, group: 15,   atomicWeight: 121.76 },
  { id: 52,  symbol: "Te", nameJa: "テルル",     nameEn: "Tellurium",     category: "半金属",         period: 5, group: 16,   atomicWeight: 127.60 },
  { id: 53,  symbol: "I",  nameJa: "ヨウ素",     nameEn: "Iodine",        category: "ハロゲン",       period: 5, group: 17,   atomicWeight: 126.90 },
  { id: 54,  symbol: "Xe", nameJa: "キセノン",   nameEn: "Xenon",         category: "希ガス",         period: 5, group: 18,   atomicWeight: 131.29 },
  { id: 55,  symbol: "Cs", nameJa: "セシウム",   nameEn: "Cesium",        category: "アルカリ金属",   period: 6, group: 1,    atomicWeight: 132.91 },
  { id: 56,  symbol: "Ba", nameJa: "バリウム",   nameEn: "Barium",        category: "アルカリ土類金属",period: 6, group: 2,   atomicWeight: 137.33 },
  { id: 57,  symbol: "La", nameJa: "ランタン",   nameEn: "Lanthanum",     category: "ランタノイド",   period: 6, group: null, atomicWeight: 138.91 },
  { id: 58,  symbol: "Ce", nameJa: "セリウム",   nameEn: "Cerium",        category: "ランタノイド",   period: 6, group: null, atomicWeight: 140.12 },
  { id: 59,  symbol: "Pr", nameJa: "プラセオジム",nameEn: "Praseodymium",category: "ランタノイド",   period: 6, group: null, atomicWeight: 140.91 },
  { id: 60,  symbol: "Nd", nameJa: "ネオジム",   nameEn: "Neodymium",     category: "ランタノイド",   period: 6, group: null, atomicWeight: 144.24 },
  { id: 61,  symbol: "Pm", nameJa: "プロメチウム",nameEn: "Promethium",  category: "ランタノイド",   period: 6, group: null, atomicWeight: null },
  { id: 62,  symbol: "Sm", nameJa: "サマリウム", nameEn: "Samarium",      category: "ランタノイド",   period: 6, group: null, atomicWeight: 150.36 },
  { id: 63,  symbol: "Eu", nameJa: "ユウロピウム",nameEn: "Europium",    category: "ランタノイド",   period: 6, group: null, atomicWeight: 151.96 },
  { id: 64,  symbol: "Gd", nameJa: "ガドリニウム",nameEn: "Gadolinium",  category: "ランタノイド",   period: 6, group: null, atomicWeight: 157.25 },
  { id: 65,  symbol: "Tb", nameJa: "テルビウム", nameEn: "Terbium",       category: "ランタノイド",   period: 6, group: null, atomicWeight: 158.93 },
  { id: 66,  symbol: "Dy", nameJa: "ジスプロシウム",nameEn: "Dysprosium",category: "ランタノイド",  period: 6, group: null, atomicWeight: 162.50 },
  { id: 67,  symbol: "Ho", nameJa: "ホルミウム", nameEn: "Holmium",       category: "ランタノイド",   period: 6, group: null, atomicWeight: 164.93 },
  { id: 68,  symbol: "Er", nameJa: "エルビウム", nameEn: "Erbium",        category: "ランタノイド",   period: 6, group: null, atomicWeight: 167.26 },
  { id: 69,  symbol: "Tm", nameJa: "ツリウム",   nameEn: "Thulium",       category: "ランタノイド",   period: 6, group: null, atomicWeight: 168.93 },
  { id: 70,  symbol: "Yb", nameJa: "イッテルビウム",nameEn: "Ytterbium", category: "ランタノイド",   period: 6, group: null, atomicWeight: 173.05 },
  { id: 71,  symbol: "Lu", nameJa: "ルテチウム", nameEn: "Lutetium",      category: "ランタノイド",   period: 6, group: null, atomicWeight: 174.97 },
  { id: 72,  symbol: "Hf", nameJa: "ハフニウム", nameEn: "Hafnium",       category: "遷移金属",       period: 6, group: 4,    atomicWeight: 178.49 },
  { id: 73,  symbol: "Ta", nameJa: "タンタル",   nameEn: "Tantalum",      category: "遷移金属",       period: 6, group: 5,    atomicWeight: 180.95 },
  { id: 74,  symbol: "W",  nameJa: "タングステン",nameEn: "Tungsten",    category: "遷移金属",       period: 6, group: 6,    atomicWeight: 183.84 },
  { id: 75,  symbol: "Re", nameJa: "レニウム",   nameEn: "Rhenium",       category: "遷移金属",       period: 6, group: 7,    atomicWeight: 186.21 },
  { id: 76,  symbol: "Os", nameJa: "オスミウム", nameEn: "Osmium",        category: "遷移金属",       period: 6, group: 8,    atomicWeight: 190.23 },
  { id: 77,  symbol: "Ir", nameJa: "イリジウム", nameEn: "Iridium",       category: "遷移金属",       period: 6, group: 9,    atomicWeight: 192.22 },
  { id: 78,  symbol: "Pt", nameJa: "白金",       nameEn: "Platinum",      category: "遷移金属",       period: 6, group: 10,   atomicWeight: 195.08 },
  { id: 79,  symbol: "Au", nameJa: "金",         nameEn: "Gold",          category: "遷移金属",       period: 6, group: 11,   atomicWeight: 196.97 },
  { id: 80,  symbol: "Hg", nameJa: "水銀",       nameEn: "Mercury",       category: "遷移金属",       period: 6, group: 12,   atomicWeight: 200.59 },
  { id: 81,  symbol: "Tl", nameJa: "タリウム",   nameEn: "Thallium",      category: "後遷移金属",     period: 6, group: 13,   atomicWeight: 204.38 },
  { id: 82,  symbol: "Pb", nameJa: "鉛",         nameEn: "Lead",          category: "後遷移金属",     period: 6, group: 14,   atomicWeight: 207.20 },
  { id: 83,  symbol: "Bi", nameJa: "ビスマス",   nameEn: "Bismuth",       category: "後遷移金属",     period: 6, group: 15,   atomicWeight: 208.98 },
  { id: 84,  symbol: "Po", nameJa: "ポロニウム", nameEn: "Polonium",      category: "後遷移金属",     period: 6, group: 16,   atomicWeight: null },
  { id: 85,  symbol: "At", nameJa: "アスタチン", nameEn: "Astatine",      category: "ハロゲン",       period: 6, group: 17,   atomicWeight: null },
  { id: 86,  symbol: "Rn", nameJa: "ラドン",     nameEn: "Radon",         category: "希ガス",         period: 6, group: 18,   atomicWeight: null },
  { id: 87,  symbol: "Fr", nameJa: "フランシウム",nameEn: "Francium",    category: "アルカリ金属",   period: 7, group: 1,    atomicWeight: null },
  { id: 88,  symbol: "Ra", nameJa: "ラジウム",   nameEn: "Radium",        category: "アルカリ土類金属",period: 7, group: 2,   atomicWeight: null },
  { id: 89,  symbol: "Ac", nameJa: "アクチニウム",nameEn: "Actinium",    category: "アクチノイド",   period: 7, group: null, atomicWeight: null },
  { id: 90,  symbol: "Th", nameJa: "トリウム",   nameEn: "Thorium",       category: "アクチノイド",   period: 7, group: null, atomicWeight: 232.04 },
  { id: 91,  symbol: "Pa", nameJa: "プロトアクチニウム",nameEn: "Protactinium",category: "アクチノイド",period: 7, group: null, atomicWeight: 231.04 },
  { id: 92,  symbol: "U",  nameJa: "ウラン",     nameEn: "Uranium",       category: "アクチノイド",   period: 7, group: null, atomicWeight: 238.03 },
  { id: 93,  symbol: "Np", nameJa: "ネプツニウム",nameEn: "Neptunium",   category: "アクチノイド",   period: 7, group: null, atomicWeight: null },
  { id: 94,  symbol: "Pu", nameJa: "プルトニウム",nameEn: "Plutonium",   category: "アクチノイド",   period: 7, group: null, atomicWeight: null },
  { id: 95,  symbol: "Am", nameJa: "アメリシウム",nameEn: "Americium",   category: "アクチノイド",   period: 7, group: null, atomicWeight: null },
  { id: 96,  symbol: "Cm", nameJa: "キュリウム", nameEn: "Curium",        category: "アクチノイド",   period: 7, group: null, atomicWeight: null },
  { id: 97,  symbol: "Bk", nameJa: "バークリウム",nameEn: "Berkelium",   category: "アクチノイド",   period: 7, group: null, atomicWeight: null },
  { id: 98,  symbol: "Cf", nameJa: "カリホルニウム",nameEn: "Californium",category: "アクチノイド", period: 7, group: null, atomicWeight: null },
  { id: 99,  symbol: "Es", nameJa: "アインスタイニウム",nameEn: "Einsteinium",category: "アクチノイド",period: 7, group: null, atomicWeight: null },
  { id: 100, symbol: "Fm", nameJa: "フェルミウム",nameEn: "Fermium",     category: "アクチノイド",   period: 7, group: null, atomicWeight: null },
  { id: 101, symbol: "Md", nameJa: "メンデレビウム",nameEn: "Mendelevium",category: "アクチノイド",  period: 7, group: null, atomicWeight: null },
  { id: 102, symbol: "No", nameJa: "ノーベリウム",nameEn: "Nobelium",    category: "アクチノイド",   period: 7, group: null, atomicWeight: null },
  { id: 103, symbol: "Lr", nameJa: "ローレンシウム",nameEn: "Lawrencium",category: "アクチノイド",   period: 7, group: null, atomicWeight: null },
  { id: 104, symbol: "Rf", nameJa: "ラザホージウム",nameEn: "Rutherfordium",category: "遷移金属",   period: 7, group: 4,    atomicWeight: null },
  { id: 105, symbol: "Db", nameJa: "ドブニウム", nameEn: "Dubnium",       category: "遷移金属",       period: 7, group: 5,    atomicWeight: null },
  { id: 106, symbol: "Sg", nameJa: "シーボーギウム",nameEn: "Seaborgium",category: "遷移金属",      period: 7, group: 6,    atomicWeight: null },
  { id: 107, symbol: "Bh", nameJa: "ボーリウム", nameEn: "Bohrium",       category: "遷移金属",       period: 7, group: 7,    atomicWeight: null },
  { id: 108, symbol: "Hs", nameJa: "ハッシウム", nameEn: "Hassium",       category: "遷移金属",       period: 7, group: 8,    atomicWeight: null },
  { id: 109, symbol: "Mt", nameJa: "マイトネリウム",nameEn: "Meitnerium",category: "遷移金属",      period: 7, group: 9,    atomicWeight: null },
  { id: 110, symbol: "Ds", nameJa: "ダームスタチウム",nameEn: "Darmstadtium",category: "遷移金属",  period: 7, group: 10,   atomicWeight: null },
  { id: 111, symbol: "Rg", nameJa: "レントゲニウム",nameEn: "Roentgenium",category: "遷移金属",     period: 7, group: 11,   atomicWeight: null },
  { id: 112, symbol: "Cn", nameJa: "コペルニシウム",nameEn: "Copernicium",category: "遷移金属",     period: 7, group: 12,   atomicWeight: null },
  { id: 113, symbol: "Nh", nameJa: "ニホニウム", nameEn: "Nihonium",      category: "後遷移金属",     period: 7, group: 13,   atomicWeight: null },
  { id: 114, symbol: "Fl", nameJa: "フレロビウム",nameEn: "Flerovium",   category: "後遷移金属",     period: 7, group: 14,   atomicWeight: null },
  { id: 115, symbol: "Mc", nameJa: "モスコビウム",nameEn: "Moscovium",   category: "後遷移金属",     period: 7, group: 15,   atomicWeight: null },
  { id: 116, symbol: "Lv", nameJa: "リバモリウム",nameEn: "Livermorium", category: "後遷移金属",     period: 7, group: 16,   atomicWeight: null },
  { id: 117, symbol: "Ts", nameJa: "テネシン",   nameEn: "Tennessine",    category: "ハロゲン",       period: 7, group: 17,   atomicWeight: null },
  { id: 118, symbol: "Og", nameJa: "オガネソン", nameEn: "Oganesson",     category: "希ガス",         period: 7, group: 18,   atomicWeight: null },
];

async function main() {
  console.log("元素データを投入中...");
  for (const element of elements) {
    await prisma.element.upsert({
      where: { id: element.id },
      update: element,
      create: element,
    });
  }
  console.log(`完了: ${elements.length} 件の元素を登録しました`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
