/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --env=staging --env-file=.dev.vars.example --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings` (hash: 11c03cc512ead33497de4d125bdaa146)
interface __BaseEnv_CloudflareBindings {
	HYPERDRIVE: Hyperdrive;
	DEPLOYMENT_ENVIRONMENT: string;
	DATABASE_TARGET: string;
	NODE_ENV: string;
	RATE_LIMIT_STORE: string;
	FRONTEND_URL: string;
	JWT_SECRET: string;
	RATE_LIMIT_KEY_SECRET: string;
	MAIL_API_URL: string;
	MAIL_API_KEY: string;
	MAIL_FROM: string;
	MAIL_ALLOWED_RECIPIENTS: string;
	MAIL_TIMEOUT_MS: string;
	RATE_LIMIT_COUNTER: DurableObjectNamespace<import("./src/worker").RateLimitCounter>;
	PASSWORD_VERIFIER: DurableObjectNamespace<import("./src/worker").PasswordVerifierDurableObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "RateLimitCounter" | "PasswordVerifierDurableObject";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEPLOYMENT_ENVIRONMENT" | "DATABASE_TARGET" | "NODE_ENV" | "RATE_LIMIT_STORE" | "FRONTEND_URL" | "JWT_SECRET" | "RATE_LIMIT_KEY_SECRET" | "MAIL_API_URL" | "MAIL_API_KEY" | "MAIL_FROM" | "MAIL_ALLOWED_RECIPIENTS" | "MAIL_TIMEOUT_MS">> {}
}
