import type { Element } from "@prisma/client";

export const ELEMENT_SEED = [
  {
    id: 1,
    symbol: "H",
    nameJa: "水素",
    nameEn: "Hydrogen",
    category: "非金属",
    period: 1,
    group: 1,
    atomicWeight: 1.008,
    etymology:
      "ギリシャ語 hydro（水）+ genes（生む）から。水を燃やすと水ができることを発見し命名（1766年、カヴェンディッシュ）",
  },
  {
    id: 2,
    symbol: "He",
    nameJa: "ヘリウム",
    nameEn: "Helium",
    category: "希ガス",
    period: 1,
    group: 18,
    atomicWeight: 4.003,
    etymology:
      "ギリシャ語 Helios（太陽神）から。地球より先に太陽のスペクトル線で発見された唯一の元素（1868年、ロッキャー）",
  },
  {
    id: 3,
    symbol: "Li",
    nameJa: "リチウム",
    nameEn: "Lithium",
    category: "アルカリ金属",
    period: 2,
    group: 1,
    atomicWeight: 6.941,
    etymology:
      "ギリシャ語 lithos（石）から。鉱石の中で発見されたアルカリ金属（1817年、アルフェドソン）",
  },
  {
    id: 4,
    symbol: "Be",
    nameJa: "ベリリウム",
    nameEn: "Beryllium",
    category: "アルカリ土類金属",
    period: 2,
    group: 2,
    atomicWeight: 9.012,
    etymology: "宝石のベリル（緑柱石）beryllosから。ベリルを分析して発見（1798年、ヴォークラン）",
  },
  {
    id: 5,
    symbol: "B",
    nameJa: "ホウ素",
    nameEn: "Boron",
    category: "半金属",
    period: 2,
    group: 13,
    atomicWeight: 10.81,
    etymology: "アラビア語 buraq（ホウ砂）から。ホウ砂を分解して単離（1808年、デービーら）",
  },
  {
    id: 6,
    symbol: "C",
    nameJa: "炭素",
    nameEn: "Carbon",
    category: "非金属",
    period: 2,
    group: 14,
    atomicWeight: 12.011,
    etymology: "ラテン語 carbo（炭、石炭）から。炭やダイヤモンドとして古代から知られた元素",
  },
  {
    id: 7,
    symbol: "N",
    nameJa: "窒素",
    nameEn: "Nitrogen",
    category: "非金属",
    period: 2,
    group: 15,
    atomicWeight: 14.007,
    etymology:
      "ギリシャ語 nitron（硝石）+ gennao（生む）から。硝石を生む物質の意（1772年、ラザフォード）",
  },
  {
    id: 8,
    symbol: "O",
    nameJa: "酸素",
    nameEn: "Oxygen",
    category: "非金属",
    period: 2,
    group: 16,
    atomicWeight: 15.999,
    etymology:
      "ギリシャ語 oxy（酸）+ gennao（生む）から。酸を生む物質と誤解されて命名（1774年、プリーストリー）",
  },
  {
    id: 9,
    symbol: "F",
    nameJa: "フッ素",
    nameEn: "Fluorine",
    category: "ハロゲン",
    period: 2,
    group: 17,
    atomicWeight: 18.998,
    etymology:
      "ラテン語 fluere（流れる）から。蛍石（fluorite）が溶剤として用いられたことにちなむ（1886年、モアッサン）",
  },
  {
    id: 10,
    symbol: "Ne",
    nameJa: "ネオン",
    nameEn: "Neon",
    category: "希ガス",
    period: 2,
    group: 18,
    atomicWeight: 20.18,
    etymology:
      "ギリシャ語 neos（新しい）から。新しく発見された気体（1898年、ラムゼーとトラヴァース）",
  },
  {
    id: 11,
    symbol: "Na",
    nameJa: "ナトリウム",
    nameEn: "Sodium",
    category: "アルカリ金属",
    period: 3,
    group: 1,
    atomicWeight: 22.99,
    etymology:
      "記号 Na はラテン語 Natrium から（アラビア語 natrun＝ソーダ）。英語名 Sodium はソーダ（soda）由来（1807年、デービー）",
  },
  {
    id: 12,
    symbol: "Mg",
    nameJa: "マグネシウム",
    nameEn: "Magnesium",
    category: "アルカリ土類金属",
    period: 3,
    group: 2,
    atomicWeight: 24.305,
    etymology:
      "ギリシャのマグネシア地方（Magnesia）から。この地域の鉱石から単離（1808年、デービー）",
  },
  {
    id: 13,
    symbol: "Al",
    nameJa: "アルミニウム",
    nameEn: "Aluminum",
    category: "後遷移金属",
    period: 3,
    group: 13,
    atomicWeight: 26.982,
    etymology:
      "ラテン語 alumen（ミョウバン）から。ミョウバンの成分として知られた金属（1827年、ヴェーラー）",
  },
  {
    id: 14,
    symbol: "Si",
    nameJa: "ケイ素",
    nameEn: "Silicon",
    category: "半金属",
    period: 3,
    group: 14,
    atomicWeight: 28.086,
    etymology: "ラテン語 silex（火打石）から。砂や石英の主成分（1824年、ベルセリウス）",
  },
  {
    id: 15,
    symbol: "P",
    nameJa: "リン",
    nameEn: "Phosphorus",
    category: "非金属",
    period: 3,
    group: 15,
    atomicWeight: 30.974,
    etymology:
      "ギリシャ語 phosphoros（光を運ぶもの）から。暗所で青白く発光する性質にちなむ（1669年、ブランド）",
  },
  {
    id: 16,
    symbol: "S",
    nameJa: "硫黄",
    nameEn: "Sulfur",
    category: "非金属",
    period: 3,
    group: 16,
    atomicWeight: 32.06,
    etymology:
      "ラテン語 sulphur から（語源諸説あり、サンスクリット語 sulveri とも）。火山地帯で古代から知られた元素",
  },
  {
    id: 17,
    symbol: "Cl",
    nameJa: "塩素",
    nameEn: "Chlorine",
    category: "ハロゲン",
    period: 3,
    group: 17,
    atomicWeight: 35.45,
    etymology:
      "ギリシャ語 chloros（黄緑色）から。特徴的な黄緑色の気体の色にちなむ（1774年、シェーレ）",
  },
  {
    id: 18,
    symbol: "Ar",
    nameJa: "アルゴン",
    nameEn: "Argon",
    category: "希ガス",
    period: 3,
    group: 18,
    atomicWeight: 39.948,
    etymology:
      "ギリシャ語 argos（怠け者）から。化学的に不活性で何とも反応しないことにちなむ（1894年、ラムゼーとレイリー）",
  },
  {
    id: 19,
    symbol: "K",
    nameJa: "カリウム",
    nameEn: "Potassium",
    category: "アルカリ金属",
    period: 4,
    group: 1,
    atomicWeight: 39.098,
    etymology:
      "記号 K はラテン語 Kalium から（アラビア語 al-qalī＝植物灰）。英語名 Potassium は potash（植物灰）由来（1807年、デービー）",
  },
  {
    id: 20,
    symbol: "Ca",
    nameJa: "カルシウム",
    nameEn: "Calcium",
    category: "アルカリ土類金属",
    period: 4,
    group: 2,
    atomicWeight: 40.078,
    etymology: "ラテン語 calx（石灰）から。石灰石・大理石の主成分（1808年、デービー）",
  },
  {
    id: 21,
    symbol: "Sc",
    nameJa: "スカンジウム",
    nameEn: "Scandium",
    category: "遷移金属",
    period: 4,
    group: 3,
    atomicWeight: 44.956,
    etymology:
      "Scandinavia（スカンジナビア）から。メンデレーエフが予言し、スカンジナビアの鉱石から発見（1879年、ニルソン）",
  },
  {
    id: 22,
    symbol: "Ti",
    nameJa: "チタン",
    nameEn: "Titanium",
    category: "遷移金属",
    period: 4,
    group: 4,
    atomicWeight: 47.867,
    etymology:
      "ギリシャ神話の巨人族 Titans（タイタン）から。精錬が極めて困難な強靭な金属にちなむ（1791年、グレガー）",
  },
  {
    id: 23,
    symbol: "V",
    nameJa: "バナジウム",
    nameEn: "Vanadium",
    category: "遷移金属",
    period: 4,
    group: 5,
    atomicWeight: 50.942,
    etymology:
      "北欧神話の美の女神 Vanadis（フレイアの別名）から。美しい多彩な色の化合物にちなむ（1801年、デルリオ）",
  },
  {
    id: 24,
    symbol: "Cr",
    nameJa: "クロム",
    nameEn: "Chromium",
    category: "遷移金属",
    period: 4,
    group: 6,
    atomicWeight: 51.996,
    etymology:
      "ギリシャ語 chroma（色）から。化合物が赤・緑・黄など様々な色を持つことにちなむ（1798年、ヴォークラン）",
  },
  {
    id: 25,
    symbol: "Mn",
    nameJa: "マンガン",
    nameEn: "Manganese",
    category: "遷移金属",
    period: 4,
    group: 7,
    atomicWeight: 54.938,
    etymology:
      "ギリシャのマグネシア地方（Magnesia）から（ラテン語 magnes＝磁石とも関連）（1774年、ガーン）",
  },
  {
    id: 26,
    symbol: "Fe",
    nameJa: "鉄",
    nameEn: "Iron",
    category: "遷移金属",
    period: 4,
    group: 8,
    atomicWeight: 55.845,
    etymology:
      "記号 Fe はラテン語 ferrum（鉄）から。英語名 Iron はゲルマン語起源。古代から知られる金属",
  },
  {
    id: 27,
    symbol: "Co",
    nameJa: "コバルト",
    nameEn: "Cobalt",
    category: "遷移金属",
    period: 4,
    group: 9,
    atomicWeight: 58.933,
    etymology:
      "ドイツ語 Kobold（地下の妖精・小悪魔）から。精錬できず鉱夫を悩ませた鉱石にちなむ（1735年、ブラント）",
  },
  {
    id: 28,
    symbol: "Ni",
    nameJa: "ニッケル",
    nameEn: "Nickel",
    category: "遷移金属",
    period: 4,
    group: 10,
    atomicWeight: 58.693,
    etymology:
      "ドイツ語 Kupfernickel（悪魔の銅）から。銅鉱石に似ているが銅が取れない「厄介な鉱石」にちなむ（1751年、クロンステット）",
  },
  {
    id: 29,
    symbol: "Cu",
    nameJa: "銅",
    nameEn: "Copper",
    category: "遷移金属",
    period: 4,
    group: 11,
    atomicWeight: 63.546,
    etymology:
      "記号 Cu はラテン語 cuprum から（Kypros＝キプロス島、古代の主産地）。古代から知られる金属",
  },
  {
    id: 30,
    symbol: "Zn",
    nameJa: "亜鉛",
    nameEn: "Zinc",
    category: "遷移金属",
    period: 4,
    group: 12,
    atomicWeight: 65.38,
    etymology:
      "ドイツ語 Zink から（語源諸説あり、ペルシャ語 sing＝石とも）。古代から青銅の成分として使われた",
  },
  {
    id: 31,
    symbol: "Ga",
    nameJa: "ガリウム",
    nameEn: "Gallium",
    category: "後遷移金属",
    period: 4,
    group: 13,
    atomicWeight: 69.723,
    etymology:
      "Gallia（フランスの古名ガリア）から。フランス人ブワボドランがスペクトル分析で発見し祖国を称えた（1875年）",
  },
  {
    id: 32,
    symbol: "Ge",
    nameJa: "ゲルマニウム",
    nameEn: "Germanium",
    category: "半金属",
    period: 4,
    group: 14,
    atomicWeight: 72.63,
    etymology:
      "Germania（ドイツの古名）から。メンデレーエフが予言した「エカシリコン」がドイツで発見（1886年、ヴィンクラー）",
  },
  {
    id: 33,
    symbol: "As",
    nameJa: "ヒ素",
    nameEn: "Arsenic",
    category: "半金属",
    period: 4,
    group: 15,
    atomicWeight: 74.922,
    etymology:
      "ギリシャ語 arsenikon（雄黄、金色の顔料）から（ペルシャ語 zarnikh＝金の物質とも）。古代から毒・顔料として知られた",
  },
  {
    id: 34,
    symbol: "Se",
    nameJa: "セレン",
    nameEn: "Selenium",
    category: "非金属",
    period: 4,
    group: 16,
    atomicWeight: 78.971,
    etymology:
      "ギリシャ語 Selene（月の女神）から。同族のテルル（地球）と対比して月にちなんで命名（1817年、ベルセリウス）",
  },
  {
    id: 35,
    symbol: "Br",
    nameJa: "臭素",
    nameEn: "Bromine",
    category: "ハロゲン",
    period: 4,
    group: 17,
    atomicWeight: 79.904,
    etymology: "ギリシャ語 bromos（悪臭）から。刺激臭の強い液体ハロゲン（1826年、バラール）",
  },
  {
    id: 36,
    symbol: "Kr",
    nameJa: "クリプトン",
    nameEn: "Krypton",
    category: "希ガス",
    period: 4,
    group: 18,
    atomicWeight: 83.798,
    etymology:
      "ギリシャ語 kryptos（隠れた）から。空気中に隠れていた希ガス（1898年、ラムゼーとトラヴァース）",
  },
  {
    id: 37,
    symbol: "Rb",
    nameJa: "ルビジウム",
    nameEn: "Rubidium",
    category: "アルカリ金属",
    period: 5,
    group: 1,
    atomicWeight: 85.468,
    etymology:
      "ラテン語 rubidus（深い赤）から。炎色反応で深紅色のスペクトル線を示すことにちなむ（1861年、ブンゼンとキルヒホッフ）",
  },
  {
    id: 38,
    symbol: "Sr",
    nameJa: "ストロンチウム",
    nameEn: "Strontium",
    category: "アルカリ土類金属",
    period: 5,
    group: 2,
    atomicWeight: 87.62,
    etymology:
      "スコットランドの村 Strontian から。この村の鉱山の鉱石から発見（1790年、クロフォード）",
  },
  {
    id: 39,
    symbol: "Y",
    nameJa: "イットリウム",
    nameEn: "Yttrium",
    category: "遷移金属",
    period: 5,
    group: 3,
    atomicWeight: 88.906,
    etymology:
      "スウェーデンの村 Ytterby から。この村の採石場からイッテルビー関連元素が多数発見された（1794年、ガドリン）",
  },
  {
    id: 40,
    symbol: "Zr",
    nameJa: "ジルコニウム",
    nameEn: "Zirconium",
    category: "遷移金属",
    period: 5,
    group: 4,
    atomicWeight: 91.224,
    etymology:
      "アラビア語 zargun（金色）から。宝石ジルコンの鮮やかな色にちなむ（1789年、クラプロート）",
  },
  {
    id: 41,
    symbol: "Nb",
    nameJa: "ニオブ",
    nameEn: "Niobium",
    category: "遷移金属",
    period: 5,
    group: 5,
    atomicWeight: 92.906,
    etymology:
      "ギリシャ神話の Niobe（タンタロスの娘）から。隣接するタンタルにちなんで「娘」の名を付けた（1801年、ハッチェット）",
  },
  {
    id: 42,
    symbol: "Mo",
    nameJa: "モリブデン",
    nameEn: "Molybdenum",
    category: "遷移金属",
    period: 5,
    group: 6,
    atomicWeight: 95.95,
    etymology:
      "ギリシャ語 molybdos（鉛）から。外見が似ていて鉛鉱石と誤認されていたことにちなむ（1778年、シェーレ）",
  },
  {
    id: 43,
    symbol: "Tc",
    nameJa: "テクネチウム",
    nameEn: "Technetium",
    category: "遷移金属",
    period: 5,
    group: 7,
    atomicWeight: null,
    etymology:
      "ギリシャ語 technetos（人工の）から。自然界に存在せず初めて人工合成された元素（1937年、ペリエとセグレ）",
  },
  {
    id: 44,
    symbol: "Ru",
    nameJa: "ルテニウム",
    nameEn: "Ruthenium",
    category: "遷移金属",
    period: 5,
    group: 8,
    atomicWeight: 101.07,
    etymology:
      "Ruthenia（ロシア・ウクライナ地域の古名）から。ウラル山脈の鉱石から発見（1844年、クラウス）",
  },
  {
    id: 45,
    symbol: "Rh",
    nameJa: "ロジウム",
    nameEn: "Rhodium",
    category: "遷移金属",
    period: 5,
    group: 9,
    atomicWeight: 102.91,
    etymology:
      "ギリシャ語 rhodon（バラ）から。化合物がバラ色であることにちなむ（1803年、ウォラストン）",
  },
  {
    id: 46,
    symbol: "Pd",
    nameJa: "パラジウム",
    nameEn: "Palladium",
    category: "遷移金属",
    period: 5,
    group: 10,
    atomicWeight: 106.42,
    etymology:
      "小惑星 Pallas（知恵の女神アテナの別名）から。発見2年前に小惑星パラスが発見されたことにちなむ（1803年、ウォラストン）",
  },
  {
    id: 47,
    symbol: "Ag",
    nameJa: "銀",
    nameEn: "Silver",
    category: "遷移金属",
    period: 5,
    group: 11,
    atomicWeight: 107.87,
    etymology:
      "記号 Ag はラテン語 argentum（銀、輝くもの）から。英語名 Silver はゲルマン語 silabar 起源。古代から知られる貴金属",
  },
  {
    id: 48,
    symbol: "Cd",
    nameJa: "カドミウム",
    nameEn: "Cadmium",
    category: "遷移金属",
    period: 5,
    group: 12,
    atomicWeight: 112.41,
    etymology:
      "ギリシャ語 kadmeia（カドミア土、亜鉛鉱石）から。亜鉛精錬の副産物として発見（1817年、シュトロマイヤー）",
  },
  {
    id: 49,
    symbol: "In",
    nameJa: "インジウム",
    nameEn: "Indium",
    category: "後遷移金属",
    period: 5,
    group: 13,
    atomicWeight: 114.82,
    etymology:
      "indigo（インジゴ青）から。スペクトル分析で鮮やかな藍色の輝線を示すことにちなむ（1863年、ライヒとリヒター）",
  },
  {
    id: 50,
    symbol: "Sn",
    nameJa: "スズ",
    nameEn: "Tin",
    category: "後遷移金属",
    period: 5,
    group: 14,
    atomicWeight: 118.71,
    etymology:
      "記号 Sn はラテン語 stannum（スズ）から。英語名 Tin はゲルマン語起源。古代から青銅の原料として知られた",
  },
  {
    id: 51,
    symbol: "Sb",
    nameJa: "アンチモン",
    nameEn: "Antimony",
    category: "半金属",
    period: 5,
    group: 15,
    atomicWeight: 121.76,
    etymology:
      "記号 Sb はラテン語 stibium から。語源は「単独で存在しない」（常に他の金属と共存する）の意とも（古代から知られた）",
  },
  {
    id: 52,
    symbol: "Te",
    nameJa: "テルル",
    nameEn: "Tellurium",
    category: "半金属",
    period: 5,
    group: 16,
    atomicWeight: 127.6,
    etymology:
      "ラテン語 Tellus（地球の女神）から。同族のセレン（月）と対比し地球にちなんで命名（1783年、ミュラー）",
  },
  {
    id: 53,
    symbol: "I",
    nameJa: "ヨウ素",
    nameEn: "Iodine",
    category: "ハロゲン",
    period: 5,
    group: 17,
    atomicWeight: 126.9,
    etymology:
      "ギリシャ語 iodes（紫色）から。加熱すると美しい紫色の蒸気を発することにちなむ（1811年、クールトワ）",
  },
  {
    id: 54,
    symbol: "Xe",
    nameJa: "キセノン",
    nameEn: "Xenon",
    category: "希ガス",
    period: 5,
    group: 18,
    atomicWeight: 131.29,
    etymology:
      "ギリシャ語 xenos（見知らぬ者）から。液体空気の蒸発残留物として発見された「見知らぬ気体」（1898年、ラムゼーとトラヴァース）",
  },
  {
    id: 55,
    symbol: "Cs",
    nameJa: "セシウム",
    nameEn: "Cesium",
    category: "アルカリ金属",
    period: 6,
    group: 1,
    atomicWeight: 132.91,
    etymology:
      "ラテン語 caesius（青みがかった灰色）から。炎色反応で特徴的な青灰色のスペクトル線を示すことにちなむ（1860年、ブンゼンとキルヒホッフ）",
  },
  {
    id: 56,
    symbol: "Ba",
    nameJa: "バリウム",
    nameEn: "Barium",
    category: "アルカリ土類金属",
    period: 6,
    group: 2,
    atomicWeight: 137.33,
    etymology:
      "ギリシャ語 barys（重い）から。重晶石（sulfate of barium）が非常に重い鉱石であることにちなむ（1808年、デービー）",
  },
  {
    id: 57,
    symbol: "La",
    nameJa: "ランタン",
    nameEn: "Lanthanum",
    category: "ランタノイド",
    period: 6,
    group: null,
    atomicWeight: 138.91,
    etymology:
      "ギリシャ語 lanthanein（隠れる）から。他の希土類元素に混じって長年発見されなかったことにちなむ（1839年、モサンデル）",
  },
  {
    id: 58,
    symbol: "Ce",
    nameJa: "セリウム",
    nameEn: "Cerium",
    category: "ランタノイド",
    period: 6,
    group: null,
    atomicWeight: 140.12,
    etymology:
      "小惑星ケレス（Ceres、ローマ神話の農業の女神）から。小惑星発見の2年後に命名（1803年、ベルセリウスとヒジンガー）",
  },
  {
    id: 59,
    symbol: "Pr",
    nameJa: "プラセオジム",
    nameEn: "Praseodymium",
    category: "ランタノイド",
    period: 6,
    group: null,
    atomicWeight: 140.91,
    etymology:
      "ギリシャ語 prasios（緑）+ didymos（双子）から。ネオジムと「緑色の双子」として分離（1885年、アウアー）",
  },
  {
    id: 60,
    symbol: "Nd",
    nameJa: "ネオジム",
    nameEn: "Neodymium",
    category: "ランタノイド",
    period: 6,
    group: null,
    atomicWeight: 144.24,
    etymology:
      "ギリシャ語 neos（新しい）+ didymos（双子）から。プラセオジムと「新しい双子」として分離（1885年、アウアー）",
  },
  {
    id: 61,
    symbol: "Pm",
    nameJa: "プロメチウム",
    nameEn: "Promethium",
    category: "ランタノイド",
    period: 6,
    group: null,
    atomicWeight: null,
    etymology:
      "ギリシャ神話の Prometheus（プロメテウス）から。神から火（核エネルギー）を奪って人間に与えた神にちなむ（1945年）",
  },
  {
    id: 62,
    symbol: "Sm",
    nameJa: "サマリウム",
    nameEn: "Samarium",
    category: "ランタノイド",
    period: 6,
    group: null,
    atomicWeight: 150.36,
    etymology:
      "鉱石サマルスカイト（Samarskite）から。ロシアの鉱山官ワシーリー・サマルスキー大佐にちなむ（1879年、ブワボドラン）",
  },
  {
    id: 63,
    symbol: "Eu",
    nameJa: "ユウロピウム",
    nameEn: "Europium",
    category: "ランタノイド",
    period: 6,
    group: null,
    atomicWeight: 151.96,
    etymology:
      "Europa（ヨーロッパ）から。ヨーロッパで発見されたことを記念して命名（1901年、ドマルセ）",
  },
  {
    id: 64,
    symbol: "Gd",
    nameJa: "ガドリニウム",
    nameEn: "Gadolinium",
    category: "ランタノイド",
    period: 6,
    group: null,
    atomicWeight: 157.25,
    etymology:
      "フィンランドの化学者 Johan Gadolin（ヨハン・ガドリン）から。希土類研究の先駆者を称えて命名（1880年、マリニャック）",
  },
  {
    id: 65,
    symbol: "Tb",
    nameJa: "テルビウム",
    nameEn: "Terbium",
    category: "ランタノイド",
    period: 6,
    group: null,
    atomicWeight: 158.93,
    etymology:
      "スウェーデンの村 Ytterby から（Ytterby → Terbium）。Ytterby採石場から複数の希土類元素が発見された（1843年、モサンデル）",
  },
  {
    id: 66,
    symbol: "Dy",
    nameJa: "ジスプロシウム",
    nameEn: "Dysprosium",
    category: "ランタノイド",
    period: 6,
    group: null,
    atomicWeight: 162.5,
    etymology:
      "ギリシャ語 dysprositos（近づきにくい）から。分離が極めて困難だったことを示す（1886年、ブワボドラン）",
  },
  {
    id: 67,
    symbol: "Ho",
    nameJa: "ホルミウム",
    nameEn: "Holmium",
    category: "ランタノイド",
    period: 6,
    group: null,
    atomicWeight: 164.93,
    etymology:
      "Holmia（ストックホルムのラテン名）から。発見者クレーヴェの出身地スウェーデンの首都（1878年）",
  },
  {
    id: 68,
    symbol: "Er",
    nameJa: "エルビウム",
    nameEn: "Erbium",
    category: "ランタノイド",
    period: 6,
    group: null,
    atomicWeight: 167.26,
    etymology:
      "スウェーデンの村 Ytterby から（Ytterby → Erbium）。テルビウムと同じ採石場から発見（1843年、モサンデル）",
  },
  {
    id: 69,
    symbol: "Tm",
    nameJa: "ツリウム",
    nameEn: "Thulium",
    category: "ランタノイド",
    period: 6,
    group: null,
    atomicWeight: 168.93,
    etymology:
      "伝説上の最北の大地 Thule（トゥーレ）から。北欧スカンジナビアで発見されたことにちなむ（1879年、クレーヴェ）",
  },
  {
    id: 70,
    symbol: "Yb",
    nameJa: "イッテルビウム",
    nameEn: "Ytterbium",
    category: "ランタノイド",
    period: 6,
    group: null,
    atomicWeight: 173.05,
    etymology:
      "スウェーデンの村 Ytterby から。Ytterby採石場から発見された希土類元素群のひとつ（1878年、マリニャック）",
  },
  {
    id: 71,
    symbol: "Lu",
    nameJa: "ルテチウム",
    nameEn: "Lutetium",
    category: "ランタノイド",
    period: 6,
    group: null,
    atomicWeight: 174.97,
    etymology:
      "Lutetia（パリのラテン名）から。フランスの発見者ウルバンが祖国の古都名を付けた（1907年）",
  },
  {
    id: 72,
    symbol: "Hf",
    nameJa: "ハフニウム",
    nameEn: "Hafnium",
    category: "遷移金属",
    period: 6,
    group: 4,
    atomicWeight: 178.49,
    etymology:
      "Hafnia（コペンハーゲンのラテン名）から。デンマークで発見されたことにちなむ（1923年、コスタとヘヴェシー）",
  },
  {
    id: 73,
    symbol: "Ta",
    nameJa: "タンタル",
    nameEn: "Tantalum",
    category: "遷移金属",
    period: 6,
    group: 5,
    atomicWeight: 180.95,
    etymology:
      "ギリシャ神話の Tantalos（タンタロス）から。分離が「tantalizing（じらす）」ほど困難だったことにちなむ（1802年、エカベルグ）",
  },
  {
    id: 74,
    symbol: "W",
    nameJa: "タングステン",
    nameEn: "Tungsten",
    category: "遷移金属",
    period: 6,
    group: 6,
    atomicWeight: 183.84,
    etymology:
      "記号 W はドイツ語 Wolfram（狼の泡・狼の糞）から。英語名はスウェーデン語 tung sten（重い石）。製錬中に錫を「食い荒らす」ことにちなむ（1783年）",
  },
  {
    id: 75,
    symbol: "Re",
    nameJa: "レニウム",
    nameEn: "Rhenium",
    category: "遷移金属",
    period: 6,
    group: 7,
    atomicWeight: 186.21,
    etymology:
      "Rhenus（ライン川のラテン名）から。ドイツの研究者夫妻が発見し、ライン川にちなんで命名（1925年、ノダック夫妻ら）",
  },
  {
    id: 76,
    symbol: "Os",
    nameJa: "オスミウム",
    nameEn: "Osmium",
    category: "遷移金属",
    period: 6,
    group: 8,
    atomicWeight: 190.23,
    etymology:
      "ギリシャ語 osme（臭気）から。四酸化オスミウムの強烈な悪臭にちなむ（1803年、テナント）",
  },
  {
    id: 77,
    symbol: "Ir",
    nameJa: "イリジウム",
    nameEn: "Iridium",
    category: "遷移金属",
    period: 6,
    group: 9,
    atomicWeight: 192.22,
    etymology:
      "ギリシャ語 iris（虹の女神・虹）から。化合物が虹のように多彩な色を持つことにちなむ（1803年、テナント）",
  },
  {
    id: 78,
    symbol: "Pt",
    nameJa: "白金",
    nameEn: "Platinum",
    category: "遷移金属",
    period: 6,
    group: 10,
    atomicWeight: 195.08,
    etymology:
      "スペイン語 platina（小さな銀）から。銀に似た白い金属として南アメリカで発見された（18世紀、ウジョアら）",
  },
  {
    id: 79,
    symbol: "Au",
    nameJa: "金",
    nameEn: "Gold",
    category: "遷移金属",
    period: 6,
    group: 11,
    atomicWeight: 196.97,
    etymology:
      "記号 Au はラテン語 aurum（曙光・輝き）から。英語名 Gold はゲルマン語で「輝くもの」。古代から知られる貴金属",
  },
  {
    id: 80,
    symbol: "Hg",
    nameJa: "水銀",
    nameEn: "Mercury",
    category: "遷移金属",
    period: 6,
    group: 12,
    atomicWeight: 200.59,
    etymology:
      "英語名は Mercury（水星・商業の神ヘルメス）、記号 Hg はラテン語 hydrargyrum（水のような銀）から。古代から知られた液体金属",
  },
  {
    id: 81,
    symbol: "Tl",
    nameJa: "タリウム",
    nameEn: "Thallium",
    category: "後遷移金属",
    period: 6,
    group: 13,
    atomicWeight: 204.38,
    etymology:
      "ギリシャ語 thallos（若緑の新芽）から。スペクトル分析で鮮やかな緑色の輝線を示すことにちなむ（1861年、クルックス）",
  },
  {
    id: 82,
    symbol: "Pb",
    nameJa: "鉛",
    nameEn: "Lead",
    category: "後遷移金属",
    period: 6,
    group: 14,
    atomicWeight: 207.2,
    etymology:
      "記号 Pb はラテン語 plumbum（鉛）から。英語の plumber（配管工）も同語源。古代ローマで水道管に使われた",
  },
  {
    id: 83,
    symbol: "Bi",
    nameJa: "ビスマス",
    nameEn: "Bismuth",
    category: "後遷移金属",
    period: 6,
    group: 15,
    atomicWeight: 208.98,
    etymology:
      "ドイツ語 Wismut から（語源は「白い物質」または「牧草地の金属」の意）。古代から単体で知られていた金属（15世紀頃）",
  },
  {
    id: 84,
    symbol: "Po",
    nameJa: "ポロニウム",
    nameEn: "Polonium",
    category: "後遷移金属",
    period: 6,
    group: 16,
    atomicWeight: null,
    etymology:
      "Polonia（ポーランドのラテン名）から。マリー・キュリーが当時ロシア支配下の祖国を称えて命名（1898年、キュリー夫妻）",
  },
  {
    id: 85,
    symbol: "At",
    nameJa: "アスタチン",
    nameEn: "Astatine",
    category: "ハロゲン",
    period: 6,
    group: 17,
    atomicWeight: null,
    etymology:
      "ギリシャ語 astatos（不安定）から。天然に痕跡量しか存在しない極めて不安定な放射性元素（1940年、コーソンら）",
  },
  {
    id: 86,
    symbol: "Rn",
    nameJa: "ラドン",
    nameEn: "Radon",
    category: "希ガス",
    period: 6,
    group: 18,
    atomicWeight: null,
    etymology:
      "Radium Emanation（ラジウムの放射）を短縮した名称。ラジウムが崩壊して生成される放射性気体（1900年、ドルン）",
  },
  {
    id: 87,
    symbol: "Fr",
    nameJa: "フランシウム",
    nameEn: "Francium",
    category: "アルカリ金属",
    period: 7,
    group: 1,
    atomicWeight: null,
    etymology:
      "Francia（フランスのラテン名）から。フランス人女性科学者ペレーが祖国を称えて命名（1939年、ペレー）",
  },
  {
    id: 88,
    symbol: "Ra",
    nameJa: "ラジウム",
    nameEn: "Radium",
    category: "アルカリ土類金属",
    period: 7,
    group: 2,
    atomicWeight: null,
    etymology:
      "ラテン語 radius（光線・放射）から。強い放射能を持つことにちなむ（1898年、キュリー夫妻）",
  },
  {
    id: 89,
    symbol: "Ac",
    nameJa: "アクチニウム",
    nameEn: "Actinium",
    category: "アクチノイド",
    period: 7,
    group: null,
    atomicWeight: null,
    etymology: "ギリシャ語 aktis（光線）から。放射線を強く発することにちなむ（1899年、ドビエルネ）",
  },
  {
    id: 90,
    symbol: "Th",
    nameJa: "トリウム",
    nameEn: "Thorium",
    category: "アクチノイド",
    period: 7,
    group: null,
    atomicWeight: 232.04,
    etymology:
      "北欧神話の雷神 Thor（トール）から。スウェーデンで発見され北欧の神にちなんで命名（1828年、ベルセリウス）",
  },
  {
    id: 91,
    symbol: "Pa",
    nameJa: "プロトアクチニウム",
    nameEn: "Protactinium",
    category: "アクチノイド",
    period: 7,
    group: null,
    atomicWeight: 231.04,
    etymology:
      "ギリシャ語 protos（最初の）+ Actinium から。崩壊してアクチニウムになる「アクチニウムの親」の意（1913年、ファヤンスら）",
  },
  {
    id: 92,
    symbol: "U",
    nameJa: "ウラン",
    nameEn: "Uranium",
    category: "アクチノイド",
    period: 7,
    group: null,
    atomicWeight: 238.03,
    etymology:
      "天王星 Uranus から。天王星発見（1781年）の8年後に発見・命名。核エネルギーの源（1789年、クラプロート）",
  },
  {
    id: 93,
    symbol: "Np",
    nameJa: "ネプツニウム",
    nameEn: "Neptunium",
    category: "アクチノイド",
    period: 7,
    group: null,
    atomicWeight: null,
    etymology:
      "海王星 Neptune から。周期表でウラン（天王星）の次に位置することにちなむ（1940年、マクミランとエイベルソン）",
  },
  {
    id: 94,
    symbol: "Pu",
    nameJa: "プルトニウム",
    nameEn: "Plutonium",
    category: "アクチノイド",
    period: 7,
    group: null,
    atomicWeight: null,
    etymology:
      "冥王星 Pluto（冥府の神）から。周期表でネプツニウム（海王星）の次に位置することにちなむ（1940年、シーボーグら）",
  },
  {
    id: 95,
    symbol: "Am",
    nameJa: "アメリシウム",
    nameEn: "Americium",
    category: "アクチノイド",
    period: 7,
    group: null,
    atomicWeight: null,
    etymology:
      "America（アメリカ大陸）から。ヨーロッパで発見されたランタノイドにならってアメリカで発見されたことにちなむ（1944年、シーボーグら）",
  },
  {
    id: 96,
    symbol: "Cm",
    nameJa: "キュリウム",
    nameEn: "Curium",
    category: "アクチノイド",
    period: 7,
    group: null,
    atomicWeight: null,
    etymology:
      "Marie & Pierre Curie（キュリー夫妻）から。放射化学の先駆者夫妻を称えて命名（1944年、シーボーグら）",
  },
  {
    id: 97,
    symbol: "Bk",
    nameJa: "バークリウム",
    nameEn: "Berkelium",
    category: "アクチノイド",
    period: 7,
    group: null,
    atomicWeight: null,
    etymology:
      "Berkeley, California から。カリフォルニア大学バークレー校で発見（1949年、シーボーグら）",
  },
  {
    id: 98,
    symbol: "Cf",
    nameJa: "カリホルニウム",
    nameEn: "Californium",
    category: "アクチノイド",
    period: 7,
    group: null,
    atomicWeight: null,
    etymology:
      "California（カリフォルニア州）と University of California から。バークリウムの次に発見（1950年、シーボーグら）",
  },
  {
    id: 99,
    symbol: "Es",
    nameJa: "アインスタイニウム",
    nameEn: "Einsteinium",
    category: "アクチノイド",
    period: 7,
    group: null,
    atomicWeight: null,
    etymology:
      "Albert Einstein（アインシュタイン）から。水爆実験の爆発塵から発見。物理学の巨人を称えた（1952年）",
  },
  {
    id: 100,
    symbol: "Fm",
    nameJa: "フェルミウム",
    nameEn: "Fermium",
    category: "アクチノイド",
    period: 7,
    group: null,
    atomicWeight: null,
    etymology:
      "Enrico Fermi（エンリコ・フェルミ）から。最初の核分裂連鎖反応を実現した物理学者を称えた（1952年）",
  },
  {
    id: 101,
    symbol: "Md",
    nameJa: "メンデレビウム",
    nameEn: "Mendelevium",
    category: "アクチノイド",
    period: 7,
    group: null,
    atomicWeight: null,
    etymology:
      "Dmitri Mendeleev（メンデレーエフ）から。周期表を創案した化学者を称えて命名（1955年、シーボーグら）",
  },
  {
    id: 102,
    symbol: "No",
    nameJa: "ノーベリウム",
    nameEn: "Nobelium",
    category: "アクチノイド",
    period: 7,
    group: null,
    atomicWeight: null,
    etymology:
      "Alfred Nobel（アルフレッド・ノーベル）から。ダイナマイト発明者・ノーベル賞創設者を称えた（1956年）",
  },
  {
    id: 103,
    symbol: "Lr",
    nameJa: "ローレンシウム",
    nameEn: "Lawrencium",
    category: "アクチノイド",
    period: 7,
    group: null,
    atomicWeight: null,
    etymology:
      "Ernest Lawrence（アーネスト・ローレンス）から。サイクロトロン発明者を称えた（1961年、シーボーグら）",
  },
  {
    id: 104,
    symbol: "Rf",
    nameJa: "ラザホージウム",
    nameEn: "Rutherfordium",
    category: "遷移金属",
    period: 7,
    group: 4,
    atomicWeight: null,
    etymology:
      "Ernest Rutherford（ラザフォード）から。原子核発見者・核物理学の父を称えた（1964年、フリョロフら）",
  },
  {
    id: 105,
    symbol: "Db",
    nameJa: "ドブニウム",
    nameEn: "Dubnium",
    category: "遷移金属",
    period: 7,
    group: 5,
    atomicWeight: null,
    etymology:
      "Dubna（ロシアの核研究都市ドゥブナ）から。JINR（合同核研究所）所在地にちなむ（1967年）",
  },
  {
    id: 106,
    symbol: "Sg",
    nameJa: "シーボーギウム",
    nameEn: "Seaborgium",
    category: "遷移金属",
    period: 7,
    group: 6,
    atomicWeight: null,
    etymology:
      "Glenn Seaborg（グレン・シーボーグ）から。超ウラン元素を多数発見したノーベル賞化学者を称えた（1974年）",
  },
  {
    id: 107,
    symbol: "Bh",
    nameJa: "ボーリウム",
    nameEn: "Bohrium",
    category: "遷移金属",
    period: 7,
    group: 7,
    atomicWeight: null,
    etymology:
      "Niels Bohr（ニールス・ボーア）から。原子モデルと量子力学の基礎を築いた物理学者を称えた（1981年）",
  },
  {
    id: 108,
    symbol: "Hs",
    nameJa: "ハッシウム",
    nameEn: "Hassium",
    category: "遷移金属",
    period: 7,
    group: 8,
    atomicWeight: null,
    etymology:
      "Hassia（ドイツのヘッセン州のラテン名）から。GSI（重イオン研究所）の所在地にちなむ（1984年）",
  },
  {
    id: 109,
    symbol: "Mt",
    nameJa: "マイトネリウム",
    nameEn: "Meitnerium",
    category: "遷移金属",
    period: 7,
    group: 9,
    atomicWeight: null,
    etymology:
      "Lise Meitner（リーゼ・マイトナー）から。核分裂の理論的解明に貢献した女性物理学者を称えた（1982年）",
  },
  {
    id: 110,
    symbol: "Ds",
    nameJa: "ダームスタチウム",
    nameEn: "Darmstadtium",
    category: "遷移金属",
    period: 7,
    group: 10,
    atomicWeight: null,
    etymology:
      "Darmstadt（ドイツの都市ダルムシュタット）から。GSI重イオン研究所の所在地にちなむ（1994年）",
  },
  {
    id: 111,
    symbol: "Rg",
    nameJa: "レントゲニウム",
    nameEn: "Roentgenium",
    category: "遷移金属",
    period: 7,
    group: 11,
    atomicWeight: null,
    etymology:
      "Wilhelm Röntgen（ヴィルヘルム・レントゲン）から。X線を発見した物理学者を称えた（1994年）",
  },
  {
    id: 112,
    symbol: "Cn",
    nameJa: "コペルニシウム",
    nameEn: "Copernicium",
    category: "遷移金属",
    period: 7,
    group: 12,
    atomicWeight: null,
    etymology: "Nicolaus Copernicus（コペルニクス）から。地動説を唱えた天文学者を称えた（1996年）",
  },
  {
    id: 113,
    symbol: "Nh",
    nameJa: "ニホニウム",
    nameEn: "Nihonium",
    category: "後遷移金属",
    period: 7,
    group: 13,
    atomicWeight: null,
    etymology:
      "Nihon（日本語で「日本」）から。理化学研究所・森田浩介らがアジア初の新元素発見。日本の誇り（2004年）",
  },
  {
    id: 114,
    symbol: "Fl",
    nameJa: "フレロビウム",
    nameEn: "Flerovium",
    category: "後遷移金属",
    period: 7,
    group: 14,
    atomicWeight: null,
    etymology:
      "Flerov Laboratory（フリョロフ核反応研究所）から。核物理学者ゲオルギー・フリョロフを称えた（1999年）",
  },
  {
    id: 115,
    symbol: "Mc",
    nameJa: "モスコビウム",
    nameEn: "Moscovium",
    category: "後遷移金属",
    period: 7,
    group: 15,
    atomicWeight: null,
    etymology: "Moscow（モスクワ）から。JINRの所在するモスクワ州にちなむ（2003年）",
  },
  {
    id: 116,
    symbol: "Lv",
    nameJa: "リバモリウム",
    nameEn: "Livermorium",
    category: "後遷移金属",
    period: 7,
    group: 16,
    atomicWeight: null,
    etymology:
      "Lawrence Livermore National Laboratory から。アメリカのローレンス・リバモア研究所にちなむ（2000年）",
  },
  {
    id: 117,
    symbol: "Ts",
    nameJa: "テネシン",
    nameEn: "Tennessine",
    category: "ハロゲン",
    period: 7,
    group: 17,
    atomicWeight: null,
    etymology:
      "Tennessee（テネシー州）から。オークリッジ国立研究所・バンダービルト大学等の所在地にちなむ（2010年）",
  },
  {
    id: 118,
    symbol: "Og",
    nameJa: "オガネソン",
    nameEn: "Oganesson",
    category: "希ガス",
    period: 7,
    group: 18,
    atomicWeight: null,
    etymology:
      "Yuri Oganessian（ユーリ・オガネシアン）から。超重元素合成の第一人者である核物理学者を称えた（2002年）",
  },
] satisfies readonly Element[];
